spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://devopsusa.com:3306/db_ecommerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

server:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: ${spring.application.name}
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://springboot-discovery.herokuapp.com/eureka