spring:
  config:
    activate:
      on-profile: development
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://devopsusa.com:3306/dev_ecommerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: release
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://devopsusa.com:3306/db_ecommerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: 80
    hostname: devopsusa-payment-service.herokuapp.com
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://springboot-discovery.herokuapp.com/eureka