version: 2
jobs:
  build:
    working_directory: ~/paymentservice
    docker:
      - image: 'circleci/openjdk:11-stretch'
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'e6:00:71:ec:7c:cd:25:43:12:37:65:38:59:51:d4:e3'
      - checkout
      - restore_cache:
          key: 'paymentservice-{{ checksum "pom.xml" }}'
      - run: 'mvn dependency:go-offline'
      - save_cache:
          paths:
            - ~/.m2
          key: 'paymentservice-{{ checksum "pom.xml" }}'
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/paymentservice.jar
      - deploy:
          machine:
            enabled: true
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
